services:
  - type: web
    name: bitwave-backend
    env: node
    rootDirectory: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: INFURA_API_KEY
        sync: false
