services:
  - type: web
    name: bitwave-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node backend/server.js"
    rootDirectory: .
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: INFURA_API_KEY
        sync: false
